export const ARTISTS = [
  "Vincent van Gogh",
  "Pablo Picasso",
  "Claude Monet",
  "Leonardo da Vinci",
  "Salvador Dali",
  "Frida Kahlo",
  "Rembrandt van Rijn",
  "Johannes Vermeer",
  "Gustav Klimt",
  "Edvard Munch",
  "Jackson Pollock",
  "Andy Warhol",
  "Georgia O'Keeffe",
  "Henri Matisse",
  "Edgar Degas",
  "Paul Cezanne",
  "Wassily Kandinsky",
  "Rene Magritte",
  "Joan Miro",
  "Marc Chagall",
  "Diego Rivera",
  "Edward Hopper",
  "Grant Wood",
  "Katsushika Hokusai",
  "Alphonse Mucha",
  "Hieronymus Bosch",
  "J.M.W. Turner",
  "Caspar David Friedrich",
  "Caravaggio",
  "Sandro Botticelli"
];

export const MOVEMENTS = [
  "Impressionism",
  "Post-Impressionism",
  "Cubism",
  "Surrealism",
  "Abstract Expressionism",
  "Pop Art",
  "High Renaissance",
  "Baroque",
  "Romanticism",
  "Realism",
  "Pointillism",
  "Fauvism",
  "Bauhaus",
  "Minimalism",
  "Art Nouveau",
  "Neoclassicism",
  "Ukiyo-e",
  "Art Deco",
  "Gothic",
  "Symbolism",
  "Futurism",
  "Constructivism",
  "Mannerism",
  "Dadaism",
  "Suprematism"
];

export const PALETTES = [
  "monochromatic blue",
  "soft pastel",
  "rich earth tones",
  "neon and cyberpunk",
  "warm autumn colors",
  "cool winter pastels",
  "high-contrast black and white with red accents",
  "nostalgic sepia",
  "deep jewel tones",
  "muted vintage",
  "vibrant primary colors",
  "muted earthy greens",
  "vibrant sunset gradients",
  "deep oceanic blues",
  "golden hour warmth",
  "high-key radiant lighting",
  "low-key chiaroscuro",
  "retro neon synthwave",
  "desaturated melancholic gray",
  "rich royal purples and golds",
  "analogous warm colors",
  "complementary orange and teal",
  "faded polaroid colors",
  "luminescent bioluminescent hues"
];

export const SUBJECTS = [
  "solitary lighthouse standing against a turbulent storm",
  "bustling futuristic cyberpunk city street",
  "quiet forest path at dawn with golden sunbeams",
  "sleepy cat resting on a sunlit windowsill",
  "majestic dragon coiled around a pile of ancient gold",
  "coffee cup steaming on a wooden table beside an open book",
  "vast galaxy swirling with vibrant nebulas and stars",
  "knight in rusted armor kneeling in an ancient ruin",
  "field of sunflowers blooming under a bright blue sky",
  "lonely astronaut floating above a fragmented planet",
  "grand gothic cathedral bathed in eerie moonlight",
  "merchant ship sailing through treacherous jagged icebergs",
  "serene koi pond with water lilies and falling cherry blossoms",
  "clockmaker's shop overflowing with intricate ticking gears",
  "masked figure dancing at an elegant Venetian ball",
  "mysterious glowing portal deep inside a crystal cave",
  "herd of wild horses galloping across a dusty plain",
  "vintage train puffing smoke across a high stone viaduct",
  "crystal palace floating high above the clouds",
  "solitary monk meditating beneath an ancient twisting banyan tree",
  "cybernetic geisha holding a neon-lit paper umbrella",
  "abandoned amusement park slowly reclaimed by creeping vines",
  "grand royal banquet hall during a lavish feast",
  "steampunk airship docking at a towering brass metropolis",
  "young woman reading a letter by a softly lit window",
  "giant mechanical leviathan rising from the dark ocean depths",
  "spooky Victorian mansion sitting on a distant foggy hill",
  "colorful hot air balloons drifting over a desert landscape",
  "fierce samurai standing in a snowy bamboo grove",
  "tangle of glowing bioluminescent mushrooms in a dark cavern",
  "mermaid lounging on a secluded rocky cove",
  "lone traveler walking towards a mysterious glowing beacon",
  "busy medieval marketplace filled with merchants and colorful tents",
  "tranquil Japanese zen garden meticulously raked",
  "futuristic hover-car speeding down a rain-slicked neon highway",
  "crown made of intertwined thorns and black roses",
  "crumbling statue of a forgotten king in a dry scorching desert",
  "wizard reading an ancient glowing grimoire in a dusty library",
  "peaceful snowy village illuminated by warm lantern light",
  "pair of elegant swans gliding on a mirrored lake",
  "gargoyle perched atop a skyscraper looking over a modern city",
  "holographic dancer performing in a dark smoky nightclub",
  "flock of ravens taking flight from a barren winter tree",
  "giant glowing hourglass slowly running out of luminous sand",
  "mystical oasis hidden within a vast deadly desert",
  "enchanted forest with trees that have faces and glowing eyes",
  "astronaut discovering a blooming flower on a barren moon",
  "cyberpunk hacker surrounded by floating holographic screens",
  "vintage acoustic guitar leaning against a brick wall",
  "majestic white stag standing proudly in a sun-dappled glade",
  "abandoned spaceship overgrown with alien flora",
  "warrior maiden resting by a small campfire under the stars",
  "bustling cafe interior on a rainy Parisian evening",
  "giant sprawling sci-fi megacity stretching to the horizon",
  "old weathered fishing boat stranded on a dry sandy beach",
  "labyrinth of impossible, Escher-like endless staircases",
  "magical apothecary shop filled with glowing potions",
  "phoenix rising triumphantly from a bed of smoldering ashes",
  "cigar-smoking detective in a dimly lit 1940s office",
  "grand library with infinite shelves stretching into darkness",
  "colossal sleeping titan forming the landscape of a mountain",
  "fairy village built softly into the branches of a giant oak",
  "glowing ethereal sword stuck firmly in a stone pedestal",
  "lone diver discovering an ancient sunken civilization",
  "pack of wolves howling at an oversized blood moon",
  "elegant pocket watch with a cracked glass face",
  "robotic assembly line constructing intricate humanoid figures",
  "whimsical carnival ride spinning rapidly in the twilight",
  "serene meadow full of floating glowing dandelion seeds",
  "dark imposing citadel made entirely of black volcanic glass",
  "wise old owl perched on a stack of ancient leather books",
  "roaring waterfall cascading into a deep turquoise pool",
  "giant floating island suspended above a endless sea of clouds",
  "ghostly galleon sailing through a dense eerie fog",
  "futuristic botanical garden housed inside a giant dome",
  "lone cowboy standing silhouetted against a desert sunset",
  "group of adventurers exploring a trap-filled temple corridor",
  "beautiful porcelain mask cracked down the middle",
  "alchemist's cluttered desk covered in scrolls and bubbling flasks",
  "city underwater enclosed in a massive glowing glass sphere",
  "symphony orchestra playing wildly in the middle of a storm",
  "solitary dark tower reaching precariously into a stormy red sky",
  "vibrant coral reef teeming with exotic alien-like fish",
  "old rusted truck abandoned in an overgrown farm field",
  "gladiator standing boldly in the center of a roaring arena",
  "beautiful geode cracked open to reveal glowing purple crystals",
  "spider weaving a web made of literal silver threads",
  "forgotten temple hidden behind a massive roaring waterfall",
  "cybernetic angel with wings of sleek glowing fiber optics",
  "cozy hearth fire burning warmly in a rustic stone cabin",
  "giant mechanical spider roaming a dystopian wasteland",
  "mysterious cloaked figure standing at a gloomy crossroads",
  "floating market boats trading vivid fruits at dawn",
  "ancient stone bridge crossing a seemingly bottomless chasm",
  "hummingbird mid-flight sipping nectar from a vibrant orchid",
  "towering monolith with glowing alien runes in a quiet valley",
  "child's discarded plush toy resting on a rainy street corner",
  "celestial goddess weaving the fabric of the night sky",
  "epic naval battle raging under an apocalyptic crimson sky",
  "majestic throne made entirely of twisting ancient roots"
];
